urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template, redirect_to


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mythoughtjot.views.home', name='home'),
    # url(r'^mythoughtjot/', include('mythoughtjot.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    #url(r'^$', 'django.contrib.auth.views.login'),
    url(r'^$', 'canvas.views.index'),
    url(r'about/$', 'django.views.generic.simple.direct_to_template', {'template':'about.html'}),
    url(r'the-team/$', 'django.views.generic.simple.direct_to_template', {'template':'team.html'}),
    #url(r'^project/(\d+)/$', redirect_to, {'url': 'project.html'}),
    
    url(r'^project/myprojects/$', 'canvas.views.myprojects'),
    url(r'^project/$', redirect_to, {'url': 'myprojects/'}),
    url(r'^myprojects/$', redirect_to, {'url': '/project/myprojects/'}),
    
    url(r'^canvas/(\d+)/$', 'canvas.views.canvas'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('registration.backends.default.urls')),
    url(r'^messages/', include('postman.urls')),
    url(r'^project/create/$', 'canvas.views.create_project'),
    url(r'^project/(\d+)/$','canvas.views.project'),
    url(r'^project/(\d+)/delete/$', 'canvas.views.project_delete'),
    url(r'^project/(\d+)/edit/$', 'canvas.views.project_edit'),
    
    url(r'^canvas/create/$', 'canvas.views.create_canvas'),
    url(r'^canvas/(\d+)/edit/$', 'canvas.views.canvas_edit'),
    url(r'^canvas/(\d+)/save/$', 'canvas.views.canvas_save'),
    url(r'^canvas/(\d+)/edit_modal/$', 'canvas.views.canvas_edit_modal'),
    url(r'^canvas/(\d+)/delete/$', 'canvas.views.canvas_delete'),
    url(r'^canvas/create_modal/$', 'canvas.views.create_canvas_modal'),
    url(r'^canvas/(\d+)/add-collaborator/$', 'canvas.views.canvas_add_collaborator'),
    url(r'^canvas/(\d+)/remove-collaborator/(\d+)/$', 'canvas.views.canvas_remove_collaborator'),
    url(r'^user/update/$', 'canvas.views.update_profile'),
    url(r'^user/(\w+)/$', 'canvas.views.view_profile'),
    url(r'^canvas/(\d+)/load_canvas/$', 'canvas.views.load_canvas'),
    url(r'^canvas/(\d+)/load_mini_collaborators/$', 'canvas.views.collaborator_mini_form'),
    url(r'^check_message_count/$', 'canvas.views.check_messages'),
)

if settings.DEBUG:
    from django.views.static import serve
    _media_url = settings.MEDIA_URL
    if _media_url.startswith('/'):
        _media_url = _media_url[1:]
        urlpatterns += patterns('',
            (r'^%s(?P<path>.*)$' % _media_url,
             serve,
            {'document_root': settings.MEDIA_ROOT}))
    del(_media_url, serve)

canvas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin


class Project(models.Model):
    title = models.CharField(max_length=75)
    description = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, blank=False, null=False, related_name="project_current_owner")
    creator = models.ForeignKey(User, blank=False, null=False, related_name = "project_original_owner")
    project_collaborators = models.ManyToManyField(User)

    def collaborators(self):
        return ', '.join([u.username for u in self.project_collaborators.all()])
    collaborators.short_description = "Collaborators"

    def __unicode__(self):
        return self.title

class Canvas(models.Model):
    title = models.CharField(max_length=75)
    created = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, blank=False, null=False, related_name="canvas_current_owner")
    creator = models.ForeignKey(User, blank=False, null=False, related_name = "canvas_original_owner")
    collaborators = models.ManyToManyField(User)
    public = models.BooleanField(default=False)
    allow_guests = models.BooleanField(default=False)
    
    #data = models.TextField()
    #iframedata = models.TextField()
    
    project = models.ForeignKey(Project)

    def __unicode__(self):
        return unicode(self.title) + ". Created by: " + unicode(self.creator) + ". From project: " + unicode(self.project.title)

    def node_count(self):
        return self.node_set.count()

    def user_names(self):
        return ', '.join([u.username for u in self.collaborators.all()])
    node_count.short_description = "# Nodes"
    user_names.short_description = "Collaborators"

    class Meta:
        verbose_name_plural = ('canvases')

class Node(models.Model):
    _data = models.TextField(max_length=10000)
    node_type = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, blank=False, null=True)
    canvas = models.ForeignKey(Canvas)
    x_pos = models.IntegerField()
    y_pos = models.IntegerField()

    def __unicode__(self):
        return "Node created by " + unicode(self.creator) + " on " + self.created.strftime("%b %d, %I:%M %p")

class UserProfile(models.Model):
    birthday = models.DateField(blank=True,null=True)
    #avatar = models.ImageField("Profile Pic", upload_to="images/", blank=True, null=True)
    user = models.ForeignKey(User, unique=True)

    #canvases = models.ManyToManyField(Canvas)

    def __unicode__(self):
        return unicode(self.user)


### Admin

class ProfileAdmin(admin.ModelAdmin):
    list_display = ["user"]

class ProjectAdmin(admin.ModelAdmin):
    list_display = ["title", "description", "collaborators","owner"]
    search_fields = ["title", "description", "project_collaborators__username", "owner__username", "creator__username", "created"]

class CanvasAdmin(admin.ModelAdmin):
    list_display = ["title", "project", "user_names", "owner", "created", "node_count"]
    list_filter = ["project", "creator", "owner"]
    search_fields = ["title", "project__title", "owner__username", "creator__username", "collaborators__username"]

class NodeAdmin(admin.ModelAdmin):
    search_fields = ["canvas__title", "creator__username", "data"]
    list_display = ["canvas", "creator", "created"]

canvas/views.py
from django.shortcuts import get_object_or_404, render_to_response, redirect
from django.core.context_processors import csrf
from mythoughtjot.canvas.models import *
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.template import RequestContext, Context
from django.forms import ModelForm
from django import forms
from django.utils import simplejson
from django.http import HttpResponse, Http404
from django.db.models import Q
from postman.models import Message



class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email')
        exclude = ["password","is_staff", "is_active","is_superuser"]
        
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UserForm, self).__init__(*args,**kwargs)
        
class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        exclude = ["user","birthday"]
        
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UserProfileForm, self).__init__(*args,**kwargs)

class ProjectForm(ModelForm):

    """
    Form for creating a project. Takes in a name and description from the form, then assigns
    the owner, creator, created date, and collaborators automagically
    """
    
    class Meta:
        model = Project
        fields = ('title','description')
        exclude = ["created","owner","creator","project_collaborators"]
        
    class Media:
        js = (
              "/media/js/forms/project.js",
              )

    def __init__(self, *args, **kwargs):
        #get the request so we can use it later
        self.request = kwargs.pop('request', None)
        super(ProjectForm, self).__init__(*args, **kwargs)


class ProjectEditForm(ModelForm):

    """
    Edit the project. Change title, description, owner, collaborators
    """

    class Meta:
        model = Project
        exclude = {'creator','created'}

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        #Get only the collaborators of the project. The default adds all available
        #users, which is bad.
        self.project_collaborators = kwargs.pop('project_collaborators', None)
        super(ProjectEditForm, self).__init__(*args, **kwargs)
        self.fields['owner'] = forms.ModelChoiceField(self.project_collaborators)
        self.fields['project_collaborators'] = forms.ModelMultipleChoiceField(self.project_collaborators)


class CanvasForm(ModelForm):

    """
    Form for creating a canvas. Takes in a canvas name, project, and a few tick boxes as options.
    Assigns owner, creator, collaborators automagically
    """

    class Meta:
        model = Canvas
        fields = ('project','title','public','allow_guests')
        
    class Media:
        js = (
              "/media/js/forms/canvas.js",
              )
        
    def __init__(self, *args, **kwargs):
        #get the request so we can use it later
        self.request = kwargs.pop('request', None)
        super(CanvasForm, self).__init__(*args, **kwargs)

    #Check to make sure the user is a collaborator of the project they selected
    def clean_project(self):
        project = self.cleaned_data['project']
        if not Project.objects.filter(pk=project.pk,project_collaborators=self.request.user).exists():
            raise forms.ValidationError("You are not a collaborator on this project.")
        return project


class CanvasEditForm(ModelForm):

    """
    Edit a canvas. Change the title, options, collaborators and project.
    """

    class Meta:
        model = Canvas
        exclude = {'creator','created'}

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        #The canvas collaborators
        self.collaborators = kwargs.pop('collaborators', None)
        #projects which the user is a collaborator on
        self.project_collaborator = kwargs.pop('project_collaborator', None)
        #All colaborators on the current project
        self.project_collaborators = kwargs.pop('project_collaborators', None)
        super(CanvasEditForm, self).__init__(*args, **kwargs)
        self.fields['canvas'] = forms.IntegerField(widget=forms.HiddenInput)
        self.fields['project'].queryset = self.project_collaborator
        self.fields['owner'].queryset = self.project_collaborators
        self.fields['collaborators'].queryset = self.collaborators


class CollaboratorForm(forms.Form):

    """
    Forn to add collaborators to a project
    """

    user = forms.CharField(label="Username",max_length=100)
    canvas = forms.IntegerField(widget=forms.HiddenInput)
    
    class Media:
        js = (
              "/media/js/forms/collaborators.js",
              )
    def clean_user(self):
        user = self.cleaned_data['user']
        canvas = self.canvas
        try:
            user_obj = User.objects.get(username__exact=user)
        except:
            raise forms.ValidationError("This user does not exist.")
        if not Canvas.objects.filter(pk=canvas,collaborators=self.request.user).exists():
            raise forms.ValidationError("You don't have permission to do that.")
        if Canvas.objects.filter(pk=canvas,collaborators=user_obj).exists(): #Doesn't raise error if user is collaborator -- fix
            raise forms.ValidationError("User is already a collaborator on this canvas.")
        return user
    
    def __init__(self, *args, **kwargs):
        #self.request = kwargs.pop('canvas', None)
        self.request = kwargs.pop('request', None)
        super(CollaboratorForm, self).__init__(*args, **kwargs)
    
class UserEditForm(ModelForm):
    class meta:
        model = User

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UserEditForm, self).__init__(*args, **kwargs)

def index(request):
    
    if request.user.is_authenticated():
        return redirect('/project/myprojects/')
    else:
        return redirect('/login/')

@login_required
def update_profile(request):
    success = False
    display_user = request.user
    profile = UserProfile.objects.get_or_create(user=display_user)
    
    if request.POST:
        uform = UserForm(data = request.POST,  instance=request.user)
        pform = UserProfileForm(data = request.POST,instance = display_user.get_profile())
        if uform.is_valid() and pform.is_valid():
            user = uform.save(commit = False)
            profile = pform.save(commit = False)
            
            profile.save()
            user.save()
            success = True
    else:
        uform = UserForm(instance = display_user)
        pform = UserProfileForm(instance = display_user.get_profile())

    return render_to_response('update_forms.html', add_csrf(request, uform=uform, pform=pform, title='Update User Profile'), context_instance=RequestContext(request))


@login_required
def create_project(request=None):

    """
    Project creation form
    """

    #request.POST or None allows you to use one line for both the
    #pre-POST form and the post-POST form
    form = ProjectForm(request.POST or None, request=request)

    if request.POST:
        if request.is_ajax():
            return_message = {'success':False, 'messages':'', 'errors':{}}
            if form.is_valid():
                try:
                    #Prep the form to be saved but don't save it
                    pre_save = form.save(commit=False)

                    #Add the user as both the owner and creator
                    pre_save.owner = request.user
                    pre_save.creator = request.user
                    #Now save the form
                    pre_save.save()
                    #then add the user as the first collaborator
                    pre_save.project_collaborators.add(request.user)
                    
                    return_message['success'] = True
            
                    return_message['messages'] = "Successfully added your project"
                    
                    #Get the id of the poject that was just saved
                    id = pre_save.pk

                    #and redirect to it
                    return_message['redirect'] = '/canvas/create/'

                except:
                    return_message['success'] = True
            
                    return_message['messages'] = "Failed to add the project"
                finally:
                    json = simplejson.dumps(return_message)
                    
                    return HttpResponse(json, mimetype='application/json')
            else:
                d={}
                for e in form.errors.iteritems():
                    d.update({e[0]:unicode(e[1])}) # e[0] is the id, unicode(e[1]) is the error HTML.
                return_message['errors'] = d
        
                json = simplejson.dumps(return_message)
        
                return HttpResponse(json, mimetype='application/json')
        else:
            if form.is_valid():  
                 #Prep the form to be saved but don't save it
                pre_save = form.save(commit=False)

                #Add the user as both the owner and creator
                pre_save.owner = request.user
                pre_save.creator = request.user
                #Now save the form
                pre_save.save()
                #then add the user as the first collaborator
                pre_save.project_collaborators.add(request.user)

                #Get the id of the poject that was just saved
                id = pre_save.pk

                #and redirect to it
                return redirect('/canvas/create/')
            
    return render_to_response('forms.html', add_csrf(request, form=form, title='Create A Project'), context_instance=RequestContext(request))



@login_required

canvas/templates/add_collaborator_short_form.html
<h2>{{title}}</h2>
<div id="messages" style="display:none"></div>
<form action="/canvas/{{canvas}}/add-collaborator/" method="POST" id="ajax_form">{% csrf_token %}
<table>
{{form.as_table}}
</table>
    <input type="submit" value="Submit" id="submit"/>
</form>

{{form.media}}

canvas/templates/canvas_1.html
{% extends "canvas/base.html" %}


{% block content %}
    <style type="text/css">
        .main { margin-left: 25px; margin-top: 30px; }

        #rtitle {
            background: #eee; font-size: 1.3em; padding: 3px; margin-top: 40px;
            padding-left: 20px; margin-bottom: -10px;
        }
        #submit { float: right; }

        img { margin-left: 85px; border: 1px solid #ccc; padding: 4px; }
    </style>

    <div class="main">
        {{ user.first_name }}
        <p>
            <h2>Canvas ID</h2>
            {{ pk }}
        </p>

        <p>
            <h2>Owner</h2>
            {{ canvas.creator }}
        </p>
        <p>
            <h2>Collaborators</h2>
            <ul>
                {% for user in canvas.collaborators.all %}
                    <li>{{ user }}</li>
                {% endfor %}
            </ul>
        </p>
        <p>
            <h2>Nodes</h2>
            <ul>
                {% for node in nodes.all %}
                    <li>{{ node }}<br />{{ node.data }}</li>
                {% endfor %}
            </ul>
        </p>
    </div>

{% endblock %}

canvas/templates/canvas_creation.html
<form action="" method="POST">{% csrf_token %}
            <table>
            {{ form.as_table }}
            </table>
        <p>
            <input style="margin-left: 320px;" type="submit" value="Submit" />
        </p>
        </form>

canvas/templates/canvas_edit_modal.html
<h2>{{title}}</h2>
<div id="messages" style="display:none"></div>
<form action="/canvas/{{ pk }}/edit_modal/" method="POST" id="ajax_form">{% csrf_token %}
<table>
{{form.as_table}}
</table>
    <input type="submit" value="Submit" id="submit"/>
</form>
<script type="text/javascript">
$(document).ready(function() {
	$("form#ajax_form").submit(function(e) {
		jQuery.ajaxSettings.traditional = true;
		canvas = $("#id_canvas").val();
		project = $("#id_project").val();
		title = $("#id_title").val();
		public_option = $("#id_public").is(':checked');
		guest_option = $("#id_allow_guests").is(':checked');
		owner = $("#id_owner").val();
		collaborators = $("#id_collaborators").val();
		csrf = $("input[name=csrfmiddlewaretoken]").val();
		$.post('/canvas/'+canvas+'/edit_modal/', {'project' : project, 'canvas':canvas,'title' : title, 'public' : public_option, 'allow_guests' : guest_option, 'owner':owner, 'collaborators':collaborators, 'csrfmiddlewaretoken': csrf}, function(data) {
			$('ul.errorlist').remove();
			if(data['success']) {
				$('#messages').html(data['messages']);
				$("#messages").css('display','block');
                setTimeout(function() {
				      $('#canvas_settings').dialog("close");
				}, 500);
		  	}else{
	  			for (error in data['errors'])
					$("#id_" + error).after(data['errors'][error]);
		  	}
			console.log(data);
		});
		jQuery.ajaxSettings.traditional = false;

		return false;
	});
});
</script>

canvas/templates/collaborator_form.html
<h2>{{title}}</h2>
<div id="messages" style="display:none"></div>
<form action="/canvas/{{canvas}}/add-collaborator/" method="POST">{% csrf_token %}
<table>
{{form.as_table}}
</table>
    <input type="submit" value="Submit" id="submit"/>
</form>

{{form.media}}

canvas/templates/collaborator_mini_form.html
<a class="add_collaborator" href="/canvas/{{ canvas.pk }}/add-collaborator/"><img src="{{ MEDIA_URL }}images/add.png" alt="Add" title="Add" /> Add a new collaborator</a>
{% if collaborators.all|length %}
    {% for user in collaborators.all %}
        <li class="update"><div class="collaborator_box"><img src="{{ MEDIA_URL }}images/waht.png" width="25px" height="25px"><a class="user_link" href="/user/{{ user.username }}/">{{ user.username }}</a>{% if request.user == canvas.owner and user != request.user %}<a class="remove_collaborator" href="/canvas/{{ canvas.pk }}/remove-collaborator/{{ user.pk }}/"><img src="{{ MEDIA_URL }}images/delete.png" alt="Remove" title="Remove" /></a>{% endif %}</div></li>
    {% endfor %}
{% else %}
	<div class="note">
	There are no collaborators
	</div>
{% endif %}

canvas/templates/forms.html
{% extends "base.html" %}

{% block title %}{{title}}{% endblock %}

{% block content %}

<h2>{{title}}</h2>
<div id="messages" style="display:none" id="simple_form"></div>
<form action="" method="POST" id="simple_form" style="overflow:hidden">{% csrf_token %}
<table>
{{form.as_table}}
</table>
    <input type="submit" value="Submit" id="submit"/>
</form>

{{form.media}}

{% endblock %}

canvas/templates/my_projects.html
{% extends "base.html" %}


{% block title %}Projects for {{ request.user.username }}{% endblock %}

{% block css %}
<style>
ul#projects {
    list-style: none;
    padding-left: 10px;
    font-size: 14px;
    line-height: 150%;
}
ul#projects p.description {
    font-size: 12px;
    margin-left: 20px;
}
ul#projects li {
    padding-left: 5px;
    padding-bottom: 15px;
}
ul#projects li span.project_title {
    font-size: 16px;
}
ul#projects li ul {
    list-style: none;
    padding-left:5px;
}
ul#projects li ul {
    padding-left: 5px;
}

ul#projects .canvases {
	-moz-border-radius: 6px;
	border-radius: 6px;
	background: #F0F0F0;
	padding: 10px;
	padding-left: 25px;
	margin-left: 25px;
}
ul#projects .canvas_list {
	margin-left: 30px;
	margin-top: 10px;
}
ul#projects .EXPANDER {
	padding: 5px;
}
</style>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
    $(document).ready(function() {
    	$(".canvases").hide();
        $(".canvas_delete").click(function(e) {
            e.preventDefault();
            if(confirm("Delete this canvas?")){
                var link = $(this).attr("href");

                $.get(link, function(data){
                    if(data){
                        alert("Successfully deleted the canvas.");
                        window.location.reload();
                    }else{
                        alert("Canvas not deleted");
                    }
                });
            }
        });
        $(".project_delete").click(function(e) {
            e.preventDefault();
            if(confirm("Delete this project and all its canvases?")){
                var link = $(this).attr("href");

                $.get(link, function(data){
                    if(data){
                        alert("Successfully deleted the project.");
                        window.location.reload();
                    }else{
                        alert("Project not deleted");
                    }
                });
            }
        });
        $(".EXPANDER").click(function(e) {
        	//alert("derp");
        	var project = $(this).attr("id");
        	$(".canvases_"+project).toggle("slow");
        	$(this).text() == "+" ? $(this).text("-") : $(this).text("+");
        });
    });
</script>
{% endblock %}

{% block header %}
<div id="header">
	
              <div id="headerLeft">
              	
              	<a href="/" title="mythoughtjot" alt="mythoughtjot"><img src="/media/images/mythoughtjotLogoAASD.png"></a>
			  </div><div class="help"></div>
        <div id="coRightHeader"> 
<h1 id="title" style="margin-top:2px; margin-bottom:2px; padding:0;">Welcome, {{ request.user.username }}</h1><span>Not {{ request.user.username}}? <a href="/logout/" style="display:inline;">Log out</a></span>
           
		</div> 
	</div>		<!-- end header-->
{% endblock %}

{% block content %}

    <h1>Projects</h1>
    <h4><a href="/project/create/"><img src="{{ MEDIA_URL }}images/add.png" alt="Add" title="Add" /> Create a project</a></h4>
    <ul id="projects">
    {% for project in projects %}

	<div class="project_listing"

       <li><span class="EXPANDER" id="{{project.pk}}">+</span> <span class="project_title"><a href="/project/{{project.pk}}/">{{ project.title }}</a></span>
        {% if request.user == project.owner %}
            <a href="/project/{{ project.pk }}/edit/"><img src="{{ MEDIA_URL }}images/edit.png" alt="Edit" title="Edit" /></a>
            <a class="project_delete" href="/project/{{ project.pk }}/delete/"><img src="{{ MEDIA_URL }}images/delete.png" alt="Delete" title="Delete" /></a>
        {% endif %}
        
       <p class="description">{{ project.description }}</p>
    <div class="canvases canvases_{{project.pk}}">   
	<h3 style="display:inline;">Canvases for this project</h3>&nbsp;
	{% if request.user in project.project_collaborators.all %}
	<a href="/canvas/create/"><img src="{{ MEDIA_URL }}images/add.png" alt="Add" title="Add" /> Create a canvas</a>
        {% endif %}
        <ul class="canvas_list">
        {% for canvas in project.canvas_set.all %}

            {% if request.user in project.project_collaborators.all or request.user == canvas.owner %}

                <li><a href="/canvas/{{canvas.pk}}/">{{ canvas.title }}</a> <a href="/canvas/{{ canvas.pk }}/edit/"><img src="{{ MEDIA_URL }}images/edit.png" alt="Edit" title="Edit" /></a> <a class="canvas_delete" href="/canvas/{{ canvas.pk }}/delete/"><img src="{{ MEDIA_URL }}images/delete.png" alt="Delete" title="Delete" /></a></li>
            {% else %}{% if request.user in canvas.collaborators.all %}
                <li>{{ canvas.title }}</li>
            {% endif %}{% endif %}

        {% endfor %}
        
        </ul>
       </div>
        </li>
		</div>
    {% endfor %}
     </ul>
    

{% endblock %}

canvas/templates/project_creation.html
<form action="" method="POST">{% csrf_token %}
            <table>
            {{ form.as_table }}
            </table>
        <p>
            <input style="margin-left: 320px;" type="submit" value="Submit" />
        </p>
        </form>

canvas/templates/project_view.html
{% extends "base.html" %}


{% block title %}{{ project.title }}{% endblock %}

{% block css %}
<style>
#project {
    list-style: none;
    padding-left: 10px;
    font-size: 14px;
    line-height: 150%;
}
#project p.description {
    font-size: 12px;
}
#project li ul {
    list-style: none;
    padding-left:5px;
}
#project li ul {
    margin-left: 25px;
}
</style>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
    $(document).ready(function() {
        $(".canvas_delete").click(function(e) {
            e.preventDefault();
            if(confirm("Delete this canvas?")){
                var link = $(this).attr("href");

                $.get(link, function(data){
                    if(data){
                        alert("Successfully deleted the canvas.");
                        window.location.reload();
                    }else{
                        alert("Canvas not deleted");
                    }
                });
            }
        });
        $(".project_delete").click(function(e) {
            e.preventDefault();
            if(confirm("Delete this project and all its canvases?")){
                var link = $(this).attr("href");

                $.get(link, function(data){
                    if(data){
                        alert("Successfully deleted the project.");
                        window.location.reload();
                    }else{
                        alert("Project not deleted");
                    }
                });
            }
        });
    });
</script>
{% endblock %}

{% block content %}
<div id="project">
    <h2>{{ project.title }}</h2>
    <br />
    <p class="description">{{ project.description }}</p>
    <br />
    <h3><a href="/project/create/"><img src="{{ MEDIA_URL }}images/add.png" alt="Add" title="Add" /> Create a project</a></h3>

        {% if request.user == project.owner %}
            <a href="/project/{{ project.pk }}/edit/"><img src="{{ MEDIA_URL }}images/edit.png" alt="Edit" title="Edit" /></a>
            <a class="project_delete" href="/project/{{ project.pk }}/delete/"><img src="{{ MEDIA_URL }}images/delete.png" alt="Delete" title="Delete" /></a>
        {% endif %}
        
       

        <ul>
        {% for canvas in project.canvas_set.all %}

            {% if request.user in project.project_collaborators.all or request.user == canvas.owner %}

                <li><a href="/canvas/{{canvas.pk}}/">{{ canvas.title }}</a> <a href="/canvas/{{ canvas.pk }}/edit/"><img src="{{ MEDIA_URL }}images/edit.png" alt="Edit" title="Edit" /></a> <a class="canvas_delete" href="/canvas/{{ canvas.pk }}/delete/"><img src="{{ MEDIA_URL }}images/delete.png" alt="Delete" title="Delete" /></a></li>
            {% else %}{% if request.user in canvas.collaborators.all %}
                <li>{{ canvas.title }}</li>
            {% endif %}{% endif %}

        {% endfor %}
        {% if request.user in project.project_collaborators.all %}
            <a href="/canvas/create/"><img src="{{ MEDIA_URL }}images/add.png" alt="Add" title="Add" /> Create a canvas</a>
        {% endif %}
        </ul>

    
</div>
{% endblock %}

canvas/templates/update_user.html
<form action="" method="POST">{% csrf_token %}
            <table>
            {{ form.as_table }}
            </table>
        <p>
            <input style="margin-left: 320px;" type="submit" value="Submit" />
        </p>
        </form>